### ISSUE TITLE
Dekoratör tasarımında düzeltme

### ISSUE THREAD

**Issue by Erkanerkisi** [yusufyilmazfr/tasarim-desenleri-turkce-kaynak#21]
Merhaba,

Aşağıdaki sınıf içerisinde bulunan writeData metodunda "super.dataSource.getFileName()" yerine "super.dataSource.writeData(obj)" kullanılmalı. Düzeltme için bana atanabilir.

https://github.com/yusufyilmazfr/tasarim-desenleri-turkce-kaynak/blob/7307647ec1548c586b232e1fd72e26aefd8967ab/decorator/java/ComporessionDecorator.java#L29

**Comment by yusufyilmazfr** [comment]
Merhaba, 
Burada aslında bir problem yok, sadece metotun içerisinde bilgi vermek için dosyanın adını çağırdım orada.
