### ISSUE TITLE
Memento ve Observer Tasarım Desenlerinde ToString() metodu Kullanımı

### ISSUE THREAD

**Issue by Natgho** [yusufyilmazfr/tasarim-desenleri-turkce-kaynak#26]
Memento ve Observer tasarım desenleri anlatılırken C# anlatımında ToString() metodu override edilmesine rağmen main içerisinde çağırılırken class ismi yerine ToString() metodu çağırılmaya devam edilmiş. Direkt olarak class'ın çağırılması da mümkün.
Örnek:

Memento:
`
// Yığındaki bir önceki duruma geçiyor.  
textOriginator.Undo();  
Console.WriteLine(textOriginator.ToString());  
`

Yerine:
`
// Yığındaki bir önceki duruma geçiyor.  
textOriginator.Undo();  
Console.WriteLine(textOriginator);  
`

**Comment by yusufyilmazfr** [comment]
Selam @Natgho, ilk bakışta evet direkt de kullanılabilirdi. Böyle de kalabilir, `ToString` metotu silinebilir de. Dilersen PR'da da bulunabilirsin. :)
