### ISSUE TITLE
Gitbook Entegrasyonu

### ISSUE THREAD

**Issue by ouzdev** [yusufyilmazfr/tasarim-desenleri-turkce-kaynak#34]
Merhaba içeriğin daha erişilebilir olması için Readme içeriğini gitbook - github entagrasyonu ile doküman haline getirdim. Şuan taslak aşamasında. Acaba içeriğin gelişimi için daha neler yapabiliriz ?

Dokümantasyona göz atmak isterseniz  https://oguzcan-genc.gitbook.io/tasarim-desenleri

Kodlar https://github.com/ouzdev/tasarim-desenleri-turkce-kaynak

**Comment by yusufyilmazfr** [comment]
Merhaba,

Öncelikle düşünceniz için teşekkür ediyorum. GitBook entegrasyonunu ilk aşamalarda uygun görmedim, amacım trafiği olabildiğince profilime ve repository'e çekmekti. Şu an repository istediğim düzeyde etkileşim aldı eğer GitBook entegrasyonu olacaksa da orijinal repository ve profilim üzerinden yayınlanması daha sağlıklı olacaktır. 

** Daha çok kişiye erişmesi noktasında ise custom bir domain alıp oradan yayınlama fikri vardı fakat iyi bir domain bulamadım, var olan da kullanılıyordu. Belki ilerleyen vakitlerde domainleri tekrar bir yoklamak gerekebilir.

**Comment by ouzdev** [comment]
Rica ederim Yusuf emeğine sağlık. Tabi ki de orjinal repoda yayınlanması daha sağlıklı, benim düşüncemde bu yönde. Eğer ilerleyen zamanda uygun görülürse PR atabilirim. Uygun bir domain bulunabilirse daha sağlıklı olur.

**Comment by yusufyilmazfr** [comment]
Teşekkür ediyorum, açıkçası GitBook entegrasyonu çok güzel olur şu anda. Dökümantasyonuna da hızlıca bir göz attım, ellerine sağlık çok hoş duruyor. 

Sadece biraz fazla sayfa geçişi olmasına içim sinmedi açıkçası, okurken sürekli bir bölünme ve yan sayfaya geçme durumu olur gibi geliyor. Okuma anında sürecin daha sürdürülebilir olması için en azından bir taslak belirleyip ona göre sayfalara bölmek daha güzel olabilir diye düşünüyorum. Sen ne dersin?

**Comment by ouzdev** [comment]
Kaynağın odak noktası tasarım desenleri olduğu için nesne yönelimli programlama ve solid ile alakalı bilgileri kendi içlerinde alt başlıklar oluşturarak tek sayfada birleştirebiliriz. Böylelikle konu bütünlüğü korunmuş ve sayfa sayısı azaltılmış olur. Bunun için menu tree i aşağıda ki gibi düzenleyebiliriz.

> - Giriş ve tanışma
> - Nesne Yönelimli Programlama (NYP Nedir ?, Nesneler ve sınıflar vb. içerikler tek sayfada alt başlıklar halinde olacak)
> - Solid Prensipleri (Solid nedir ?, Solid prensipleri içerikleri tek sayfada alt başlıklar halinde olacak.)
> - Tasarım Desenleri
>    - Creational (Oluşturucu) Tasarım Desenleri
>    - Structural (Yapısal) Tasarım Desenleri
>    - Behavioral (Davranışsal) Tasarım Desenleri
> - Kapanış & Kaynakça

**Comment by yusufyilmazfr** [comment]
@ouzdev bence de çok hoş olur. Üst kısımlar kendi içlerinde alt başlıklar ile devam eder. Tasarım Desenleri kısmı ise kendi içerisinde sayfalar halinde ilerler, şu anki hali de öyle gördüğüm kadarıyla, var olan hali bile uygun. Müsaitliğin varsa bu değişikliklerle birlikte PR alabiliriz. ✌️🎉

**Comment by ouzdev** [comment]
Bahsettiğim değişiklikleri önümüzdeki hafta içerisinde yapmayı planlıyorum şimdilik bu haliyle PR alabiliriz 🎉

**Comment by yusufyilmazfr** [comment]
O değişiklikler geldiğinde direkt merge ederiz. :) https://github.com/yusufyilmazfr/tasarim-desenleri-turkce-kaynak/pull/35

**Comment by ouzdev** [comment]
Yusuf tekrardan merhaba
Gerekli düzenlemeleri yaptım kontrol sağlayıp merge alabiliriz

**Comment by yusufyilmazfr** [comment]
Eline sağlık @ouzdev, ilk fırsatta inceleyeceğim.

**Comment by yusufyilmazfr** [comment]
Done! 🚀 https://github.com/yusufyilmazfr/tasarim-desenleri-turkce-kaynak/pull/35

**Comment by yusufyilmazfr** [comment]
@ouzdev selam, ufak bir ricam olacaktı da senden, sana ait GitBook üzerinden de repoya trafik var gibi gördüm de, rica etsem issue için açtığım o sayfayı kaldırma imkanımız var mıdır acaba? Kaynak için 2 sayfanın olmaması daha sağlıklı olur da.

**Comment by ouzdev** [comment]
@yusufyilmazfr Selam aslında unlisted olarak paylaşmıştım ama kaldırayım o zaman. Kusura bakma biraz geç oldu bazı sebeblerden ötürü :)
